# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 21:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_tracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='tracker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tracker.Tracker'),
        ),
    ]
