# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_log_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='text',
            field=models.TextField(),
        ),
    ]
